interface Window {
	translations: any;
}

window.translations = {
	en: {
		home: {
			title: "HOME"
		},
		archive: {
			title: "ARCHIVE"
		},
		blog: {
			title: "BLOG"
		},
		about: {
			title: "ABOUT",
			text: "<li><p>“BarCamp Yerevan” was first held on April 17-19, 2009. Armenian IT and new media specialists fell in love with the new type of “unconference” and each successive BarCamp, in 2010, 2011, 2012 and 2013 attracted more and more people. In 2009 we only had 400 participants. Last year, in 2013, the number of developers, hackers, geeks, bloggers, journalists and online activists exceeded 1200. Check out this video to get a glimpse of what it felt to be in “BarCamp Yerevan 2011″. Our favorite bit is the afterparty of course ;)</p><img src='/build/assets/images/we.jpg' class='we'><p>“BarCamp Yerevan 2015″ will be held pretty soon. We strongly urge you to <a href='https://www.eventbrite.co.uk/e/barcamp-yerevan-2015-tickets-16660816952' target='_blank'>REGISTER</a> in order to take part in the event.</p></li><li><h3>What is the BarCamp?</h3><p>BarCamp is a brand new event, originating in the Silicon Valley of USA in 2005 that has become widespread throughout the world.</p><p>Filling in presentation wall<br/>BarCamp is usually a “œnon-conference” in the sphere of information technology or “œIT,” new media and Internet. A “œnon-conference” is the unofficial, informal part of the conference supporting open discussions and a free exchange of ideas and opinions</p><p>First BarCamp in History<br/>The philosophy of BarCamp is the following: all presentations are given by participants themselves, with no formally invited guest speakers and without the formality of traditional conference. Most revealing, the schedule of events is “œproduced” by the participants of the conference and is formed only after the conference opens, as participants add the presentations they want to hold on a white board.</p></li><li><h3>Our region</h3><p>The first ever BarCamp in the former Soviet Union was organized in Kyiv in October 2007. It brought together about 300 people from Ukraine, Belarus, Kazakhstan, Latvia, Russia, Kyrgyzstan, Poland, and other countries from the region and featured around 45 presentations.</p><p>After BarCamp Kiev, there was “œBarCamp Baltics” in Riga (February 2008) and “œBarcamp Caucasus” in Tbilisi (June 2008). The wave of BarCamps continues.</p></li><li><h3>Target Group</h3><p>The main target audience of the BarCamp is Web project managers, entrepreneurs, new media activists, designers, educators and all business professionals who are building the next generation Web.</p></li>"
		},
		faq: {
			title: "FAQ",
			frequentlyAsked: "Frequently asked<br/>questions",
			questions: "<li><h3>I have not received a confirmation email after registration. What should I do?</h3><p>There are no confirmation emails after the registration. If you see the message \"Thanks, your registration is complete\" , it means that your  registration is confirmed</p></li><li><h3>Should I register, if I'm not planning to make a presentation?</h3><p>Yes! Registration is desirable for all participants, including those, who only come to watch.</p></li><li><h3>Where is the timetable of the event. When should I come?</h3><p>The BarCamp agenda is made by the participants themselves. Our timetable looks like this. There will be a blank timetable board in the corridor, where anyone can register the presentation they are planning to make. As always, this year we will have guest speakers from abroad, who will make their presentations in the Big Hall. The timetable of the Big Hall will be available on this website</p></li><li><h3>Can I come late or join the BarCamp only for one day?</h3><p>Yes, you can.</p></li><li><h3>When will we get the badges?</h3><p>When you come to BarCamp approach the volunteers in the corridor where registration process is taking place. They will look up your name in the registration list and give your your badge and T-shirt.</p></li><li><h3>Can I come and present a website that I've created?</h3><p>Direct presentations of a website or a company are forbidden. We do not allow advertising of any type during the barcamp. Try to present an interesting technical solution, idea or topic that can teach something to the participants and feel free to use examples from your company or website. The key requirement is to make an interesting and/or useful presentation for the audience. Remember, our particiapants will \"vote with their feet\" and boring presentations will eventually end up facing an empty room. That's not something you'd want, would you?</p></li><li><h3>Who is the organizer of the event.</h3><p>BarCamp is organized by independent people solely on volunteer basis. Internews Armenia and individuals, who work for various companies help in organizing the event. The Big Hall and several rooms at the American University of Armenia are rented for the purposes of holding a BarCamp. The general sponsor of this year's BarCamp is U!Com.</p></li><li><h3>Will presentations be filmed or broadcast online?</h3><p>There will be live video streaming from all presentation rooms. The links to video streams will be available on our website.</p></li><li><h3>What formats should the presentations be in?</h3><p>Bring .ppt presentations and make sure to use Unicode Armenian fonts (type your text using Sylfaen or Arian AMU fonts.</p></li>"
		}
	},
	hy: {
		home: {
			title: ""
		},
		archive: {
			title: ""
		},
		blog: {
			title: ""
		},
		about: {
			title: "Մեր Մասին",
			text: "<li><p>“ԲարՔեմփ Երևանը” առաջին անգամ անցկացվեց 2009 թվականի ապրիլի 17-19-ը։ Նոր ձևաչափով չկոնֆերանսը գրավեց տեղեկատվական տեխնոլոգիաների և նոր մեդիայի ոլորտի մասնագետներին և յուրաքանչյուր հաջորդ “ԲարՔեմփ Երևան” միջոցառումներին` 2010, 2011, 2012, 2013 թվականներին, հետաքրքրվողների և մասնակիցների թիվը սկսեց աճել։ Եթե 2009-ին մենք ունեցանք 400 մասնակից, 2011-ին ավելի քան 800, ապա 2013-ին “ԲարՔեմփ Երևան”-ի մասնակիցների թիվը գերազանցեց 1500-ը:</p><img src='/build/assets/images/we.jpg' class='we'></li><li><h3>Ի՞նչ է ԲարՔեմփը</h3><p>ԲարՔեմփը միջոցառումներ կազմակերպելու նոր ձևաչափ է, որն առաջին անգամ կիրառվել է 2005 թ-ին ԱՄՆ-ում՝ Silicon Valley-ում, և հետո ստացել է լայն տարածում ամբողջ աշխարհում։</p><p>Սովորաբար ԲարՔեմփ են անվանում Տեղեկատվական Տեխնոլոգիաների, Ինտերնետի և Նոր Մեդիաների թեմաներով չկոնֆերանսները։ Չկոնֆերանս, քանի որ միջոցառումն անցնում է ոչ ֆորմալ մթնոլորտում, ինչը ապահովում է բաց քննարկումներ և մտքերի ազատ փոխանակում։</p><p>ԲարՔեմփի փիլիսոփայությունը հետևյալն է. չկան հատուկ հրավիրված բանախոսներ, մասնակիցներն իրենք են զեկուցումներ անում, և քննարկում դրանք։ Հակառակ ավանդական կոնֆերանսի՝ այստեղ օրակարգը ձևավորվում է մասնակիցների կողմից և վերջնական տեսք է ստանում միայն միջոցառման բացումից հետո. մասնակիցները սպիտակ թղթի վրա ըստ ժամերի դասավորում են իրենց զեկուցումների թեմաները։</p></li><li><h3>Մեր տարածաշրջանում</h3><p>Նախկին Խորհրդային Միության տարածքում առաջին ԲարՔեմփը կազմակերպվել է Կիևում 2007թ.-ի հոկտեմբերին, որին ասնակցում էր ավելի քան 300 մարդ՝ Ուկրաինայից, Բելառուսից, Ղրղզստանից, Լատվիայից, Ռուսաստանից, Ղազախստանից, Լեհաստանից և այլ երկրներից։</p><p>“ԲարՔեմփ Կիև”-ին 2008թ.-ի փետրվարին հաջորդեց “ԲարՔեմփ Բալթիքսը” Ռիգայում, հունիսին՝ “ԲարՔեմփ Կովկասը” Թբիլիսիում։ ԲարՔեմփերի ալիքը շարունակվում է։</p></li><li><h3>Թիրախ Խումբ</h3><p>ԲարՔեմփի հիմնական թիրախ խումբը կազմում են նոր մեդիաների, ՏՏ, Ինտերնետ և թվային տեխնոլոգիաներում ներգրավված ընկերությունների մասնագետները, ղեկավարները, գործարարները, ուսանողները, ակտիվիստները, դասախոսները, բլոգերներն ու լրագրողները և բոլոր նրանք, ով ստեղծում է նոր սերնդի համաշխարհային Սարդոստայն։</p></li>"
		},
		faq: {
			title: "ՀՏՀ",
			frequentlyAsked: "",
			questions: "<li><h3>Ես գրանցվել եմ, բայց հաստատման նամակ չի եկել, ի՞նչ անեմ:</h3><p>Գրանցվելուց հետո հաստատման նամակ չի գալիս: Եթե գրանցման վերջում տեսնում եք հաղորդագրություն \"Thanks, your registration is complete\", նշանակում է, որ ձեր գրանցումը հաստատված է:</p></li><li><h3>Պե՞տք է արդյոք գրանցվել, եթե ներկայացում չեմ անելու:</h3><p>Այո, բոլոր մասնակիցների, ներառյալ հանդիսատեսների համար գրանցումը պարտադիր է:</p></li><li><h3>Որտե՞ղ է միջոցառման օրակարգը: Ո՞ր ժամին պիտի գանք:</h3><p>Միջոցառման օրակարգը կազմվում է հենց մասնակիցների կողմից: Մեր ժամանակացույցը այս տեսքն ունի: Միջանցքում դրված է լինում դատարկ ժամատախտակ, որտեղ ցանկացած մարդ կարող է գրանցել իր ներկայացման թեման: Այս տարի ևս Բարքեմփին կլինեն արտասահմանից հրավիրված հյուրեր, ովքեր ներկայացում են անելու մեծ դահլիճում: Դրա օրակարգը այստեղ է:</p></li><li><h3>Կարո՞ղ եմ ավելի ուշ միանալ, կամ միայն մեկ օրը գալ:</h3><p>Այո, կարող եք, սահմանափակում չկա:</p></li><li><h3>Բեյջերը ե՞րբ ենք ստանալու:</h3><p>Երբ ժամանում եք ԲարՔեմփի վայր, մոտեցեք միջանցքում տեղակայված կամավորների սեղանին: Նրանք կփնտրեն ձեր անունը գրանցվածների ցուցակում և կտրամադրեն ձեզ շապիկ և բեյջ:</p></li><li><h3>Կարո՞ղ եմ գալ, ներկայացնել իմ ստեղծած կայքը:</h3><p>Որևէ կայք կամ ընկերություն ուղղակի ներկայացնելը ԲարՔեմփի ընթացքում չի թույլատրվում: Ցանկացած տիպի գովազդ խստիվ արգելվում է: Փոխարենը մտածեք մի հետաքրքիր տեխնիկական լուծում ներկայացնել, հետաքրքիր գաղափար կամ ինչ-որ ուսուցողական թեմա, թեկուզ ձեր ընկերության կամ կայքի օրինակով: Կարևորը որ ներկայացումը հետաքրքիր և/կամ օգտակար լինի լսարանի համար: Հիշեք որ մասնակիցները քվեարկելու են “ոտքերով”, այսինքն անհետաքրքիր ներկայացումներին դատարկ լսարաններ են սպասվում: Չեք ուզի, չէ՞:</p></li><li><h3>Ո՞վ է միջոցառման կազմակերպիչը:</h3><p>Միջոցառումը կազմակերպվում է անկախ մարդկանց կողմից՝ կամավորական սկզբունքով: ԲարՔեմփին կազմակերպչական հարցերով աջակցում են Ինտերնյուս Հայաստանը և անհատներ, ովքեր տարբեր ընկերություններում են աշխատում: Բարքեմփի համար վարձակալվում են Ամերիկյան համալսարանի դահլիճը և սենյակները. Իսկ միջոցառման գլխավոր հովանավորն է Յուքոմ ընկերությունը:</p></li><li><h3>Արդյո՞ք ելույթները տեսագրվելու են, կամ օնլայն կարո՞ղ ենք հետևել:</h3><p>Այս տարի բոլոր սենյակներից livestream է լինելու: Հղումները կտեղադրվեն մեր կայքում:</p></li><li><h3>Ի՞նչ ֆորմատով պետք է բերել պրեզենտացիաները:</h3><p>.ppt բերեք և հայերենի դեպքում միայն Յունիքոդ՝ Sylfaen կամ Arian AMU տառատեսակներով:</p></li>"
		}
	}
};